- name: Log in to DockerHub
  docker_login:
    username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"

- name: Run API
  docker_container:
    name: backend-api
    image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/tp-devops-simple-api:latest"
    state: started
    restart_policy: always
    env:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: "jdbc:mysql://db:3306/mydb"
    networks:
      - name: my_network