- name: Log in to DockerHub
  docker_login:
    username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"

- name: Run HTTPD
  docker_container:
    name: httpd
    image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/tp-devops-httpd:latest"
    state: started
    restart_policy: always
    ports:
      - "80:80"
    networks:
      - name: my_network