name: CI devops 2025

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend:
    name: Test Backend (Maven)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test backend with Maven
        run: mvn clean verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  build-and-push-docker-image:
    name: Build & Push Docker Images
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-db:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true

  deploy:
    name: Deploy to Server
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ansible
        run: sudo apt update && sudo apt install -y ansible sshpass
      - name: Set up SSH key
        run: sudo mkdir -p /mnt/c/Users/julie/Documents/5A/DevOps/tp1_copy/DevOpsTP/ansible/inventories/ && echo "${{ secrets.SERVER_PRIVATE_KEY }}" > /mnt/c/Users/julie/Documents/5A/DevOps/tp1_copy/DevOpsTP/ansible/inventories/id_rsa && chmod 600 /mnt/c/Users/julie/Documents/5A/DevOps/tp1_copy/DevOpsTP/ansible/inventories/id_rsa

      - name: Add server to known_hosts
        run: ssh-keyscan -H julien.thepaut.takima.cloud >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --private-key /mnt/c/Users/julie/Documents/5A/DevOps/tp1_copy/DevOpsTP/ansible/inventories/id_rsa -u admin --become