name: CI devops 2025

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend:
    name: Test Backend (Maven)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test backend with Maven
        run: mvn clean verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  build-and-push-docker-image:
    name: Build & Push Docker Images
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-db:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true

  deploy:
    name: Deploy to Server
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using Ansible
        uses: dawidd6/action-ansible-playbook@v2.1.4
        with:
          playbook: ansible/deploy.yml
          inventory: ansible/inventory/hosts.ini
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          extra-vars: |
            dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}
            dockerhub_token=${{ secrets.DOCKERHUB_TOKEN }}